// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByVFzRjG4qpTw0NjY7ziUwPtgrSML1ylA',
    appId: '1:5764322017:android:cda1b7187f49e85f7b9da0',
    messagingSenderId: '5764322017',
    projectId: 'fitchair1',
    databaseURL: 'https://fitchair1-default-rtdb.firebaseio.com',
    storageBucket: 'fitchair1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI7elH0sgcZhJ-VBhNZx_fd1IW746pGx8',
    appId: '1:5764322017:ios:f6ef20149a3210867b9da0',
    messagingSenderId: '5764322017',
    projectId: 'fitchair1',
    databaseURL: 'https://fitchair1-default-rtdb.firebaseio.com',
    storageBucket: 'fitchair1.appspot.com',
    iosBundleId: 'com.example.appint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfpUToP-jJfRM3RFJwen7hf5LmR6ymDBI',
    appId: '1:5764322017:web:205fe6459ea7c7a07b9da0',
    messagingSenderId: '5764322017',
    projectId: 'fitchair1',
    authDomain: 'fitchair1.firebaseapp.com',
    databaseURL: 'https://fitchair1-default-rtdb.firebaseio.com',
    storageBucket: 'fitchair1.appspot.com',
    measurementId: 'G-CPFCPFESRC',
  );

}